// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package gateway

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Group int32

const (
	Group_User      Group = 0
	Group_ADMIN     Group = 1
	Group_DEVELOPER Group = 2
)

var Group_name = map[int32]string{
	0: "User",
	1: "ADMIN",
	2: "DEVELOPER",
}

var Group_value = map[string]int32{
	"User":      0,
	"ADMIN":     1,
	"DEVELOPER": 2,
}

func (x Group) String() string {
	return proto.EnumName(Group_name, int32(x))
}

func (Group) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

type GetUserRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UpdateUserRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateUserRequest) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

type UserResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserResponse) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

type UserGroupRequest struct {
	Group                Group    `protobuf:"varint,1,opt,name=group,proto3,enum=gateway.Group" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserGroupRequest) Reset()         { *m = UserGroupRequest{} }
func (m *UserGroupRequest) String() string { return proto.CompactTextString(m) }
func (*UserGroupRequest) ProtoMessage()    {}
func (*UserGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *UserGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserGroupRequest.Unmarshal(m, b)
}
func (m *UserGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserGroupRequest.Marshal(b, m, deterministic)
}
func (m *UserGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGroupRequest.Merge(m, src)
}
func (m *UserGroupRequest) XXX_Size() int {
	return xxx_messageInfo_UserGroupRequest.Size(m)
}
func (m *UserGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserGroupRequest proto.InternalMessageInfo

func (m *UserGroupRequest) GetGroup() Group {
	if m != nil {
		return m.Group
	}
	return Group_User
}

type UsersResponse struct {
	Group                Group           `protobuf:"varint,1,opt,name=group,proto3,enum=gateway.Group" json:"group,omitempty"`
	Users                []*UserResponse `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UsersResponse) Reset()         { *m = UsersResponse{} }
func (m *UsersResponse) String() string { return proto.CompactTextString(m) }
func (*UsersResponse) ProtoMessage()    {}
func (*UsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *UsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersResponse.Unmarshal(m, b)
}
func (m *UsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersResponse.Marshal(b, m, deterministic)
}
func (m *UsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersResponse.Merge(m, src)
}
func (m *UsersResponse) XXX_Size() int {
	return xxx_messageInfo_UsersResponse.Size(m)
}
func (m *UsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UsersResponse proto.InternalMessageInfo

func (m *UsersResponse) GetGroup() Group {
	if m != nil {
		return m.Group
	}
	return Group_User
}

func (m *UsersResponse) GetUsers() []*UserResponse {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterEnum("gateway.Group", Group_name, Group_value)
	proto.RegisterType((*GetUserRequest)(nil), "gateway.GetUserRequest")
	proto.RegisterType((*UpdateUserRequest)(nil), "gateway.UpdateUserRequest")
	proto.RegisterType((*UserResponse)(nil), "gateway.UserResponse")
	proto.RegisterType((*UserGroupRequest)(nil), "gateway.UserGroupRequest")
	proto.RegisterType((*UsersResponse)(nil), "gateway.UsersResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 384 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xc1, 0x6a, 0xdb, 0x40,
	0x10, 0xad, 0x64, 0xab, 0xae, 0xc7, 0xb6, 0xaa, 0x0e, 0xb8, 0x55, 0x45, 0x0f, 0x42, 0xf4, 0x60,
	0x6c, 0xb0, 0xc0, 0xbd, 0x94, 0xde, 0x5a, 0x2c, 0x8c, 0xa1, 0xae, 0x8b, 0x82, 0x73, 0x5f, 0x47,
	0x8b, 0x10, 0xd8, 0x5a, 0x45, 0xbb, 0x76, 0x30, 0x21, 0x87, 0xe4, 0x17, 0xf2, 0x69, 0xf9, 0x85,
	0x7c, 0x48, 0xd8, 0x95, 0x23, 0xd9, 0x21, 0x84, 0x90, 0xdb, 0x8c, 0xe6, 0xbd, 0xa7, 0xb7, 0x6f,
	0x06, 0x60, 0xc3, 0x69, 0x3e, 0xcc, 0x72, 0x26, 0x18, 0x36, 0x62, 0x22, 0xe8, 0x05, 0xd9, 0x39,
	0xdf, 0x62, 0xc6, 0xe2, 0x15, 0xf5, 0x49, 0x96, 0xf8, 0x24, 0x4d, 0x99, 0x20, 0x22, 0x61, 0x29,
	0x2f, 0x60, 0x4e, 0x8b, 0xac, 0x92, 0x2d, 0x2d, 0x1a, 0xcf, 0x05, 0x73, 0x42, 0xc5, 0x82, 0xd3,
	0x3c, 0xa4, 0xe7, 0x1b, 0xca, 0x05, 0x9a, 0xa0, 0x27, 0x91, 0xad, 0xb9, 0x5a, 0xaf, 0x19, 0xea,
	0x49, 0xe4, 0x4d, 0xe1, 0xd3, 0x22, 0x8b, 0x88, 0xa0, 0x2f, 0x80, 0x10, 0xa1, 0x9e, 0x92, 0x35,
	0xb5, 0x75, 0xf5, 0x45, 0xd5, 0x68, 0x41, 0x8d, 0xc4, 0xd4, 0xae, 0xb9, 0x5a, 0xcf, 0x08, 0x65,
	0xe9, 0x8d, 0xa1, 0x5d, 0x88, 0xf0, 0x8c, 0xa5, 0x9c, 0xbe, 0x51, 0xe5, 0x27, 0x58, 0x52, 0x65,
	0x92, 0xb3, 0x4d, 0xf6, 0xe8, 0xe7, 0x3b, 0x18, 0xb1, 0xec, 0x95, 0x98, 0x39, 0x32, 0x87, 0xfb,
	0x28, 0x86, 0x05, 0xaa, 0x18, 0x7a, 0x4b, 0xe8, 0x48, 0x26, 0x2f, 0x0d, 0xbc, 0x8a, 0x86, 0x03,
	0x30, 0x64, 0xca, 0xdc, 0xd6, 0xdd, 0x5a, 0xaf, 0x35, 0xea, 0x96, 0xa8, 0xc3, 0xc7, 0x84, 0x05,
	0xa6, 0x3f, 0x00, 0x43, 0x91, 0xf1, 0x03, 0xd4, 0xe5, 0xdc, 0x7a, 0x87, 0x4d, 0x30, 0x7e, 0x8f,
	0x67, 0xd3, 0x7f, 0x96, 0x86, 0x1d, 0x68, 0x8e, 0x83, 0xd3, 0xe0, 0xef, 0xfc, 0x7f, 0x10, 0x5a,
	0xfa, 0xe8, 0x5a, 0x87, 0x96, 0x04, 0x9d, 0xd0, 0x7c, 0x9b, 0x9c, 0x51, 0x9c, 0x41, 0x63, 0xbf,
	0x0d, 0xfc, 0x52, 0x79, 0x39, 0xda, 0x8f, 0xf3, 0xfc, 0xef, 0x3d, 0xbc, 0xb9, 0xbb, 0xbf, 0xd5,
	0xdb, 0x08, 0xbe, 0xf4, 0xe1, 0x5f, 0x26, 0xd1, 0x15, 0x86, 0xe5, 0x72, 0xff, 0xec, 0x0a, 0x53,
	0x5f, 0x8f, 0xc8, 0x87, 0x11, 0x3a, 0x9f, 0x8f, 0x46, 0x65, 0x46, 0x5e, 0x47, 0x09, 0x37, 0xd0,
	0x50, 0xc2, 0x38, 0x07, 0xa8, 0xce, 0x01, 0x9d, 0x8a, 0xf4, 0xf4, 0x46, 0x9c, 0x2a, 0xcd, 0x60,
	0x9d, 0x89, 0x9d, 0xd7, 0x55, 0x42, 0x1f, 0x9d, 0x03, 0x87, 0xbf, 0xb4, 0xfe, 0xf2, 0xbd, 0x3a,
	0xc4, 0x1f, 0x0f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x68, 0x2a, 0xa8, 0xe0, 0xca, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*UserResponse, error)
	GetUserByGroup(ctx context.Context, in *UserGroupRequest, opts ...grpc.CallOption) (*UsersResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*Empty, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/gateway.UserService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserByGroup(ctx context.Context, in *UserGroupRequest, opts ...grpc.CallOption) (*UsersResponse, error) {
	out := new(UsersResponse)
	err := c.cc.Invoke(ctx, "/gateway.UserService/GetUserByGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/gateway.UserService/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	GetUser(context.Context, *GetUserRequest) (*UserResponse, error)
	GetUserByGroup(context.Context, *UserGroupRequest) (*UsersResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*Empty, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) GetUser(ctx context.Context, req *GetUserRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedUserServiceServer) GetUserByGroup(ctx context.Context, req *UserGroupRequest) (*UsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserByGroup not implemented")
}
func (*UnimplementedUserServiceServer) UpdateUser(ctx context.Context, req *UpdateUserRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway.UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserByGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserByGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway.UserService/GetUserByGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserByGroup(ctx, req.(*UserGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway.UserService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "GetUserByGroup",
			Handler:    _UserService_GetUserByGroup_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserService_UpdateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
